name: Go CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build and Test
        run: |
          go build -v -o app ./...
          go test -v ./...

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app

  build-and-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
          build-args: |
            BINARY=app
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
